# This action.yml provides a GitHub Action for building NCEP libraries with
# CMake.
# Alex Richert, April 2024
name: 'Build NCEPLIBS'
description: 'Builds and installs requested versions/configurations of various NCEPLIBS'

inputs:
  jasper-version:
    default: ""
  jasper-cmake-args:
    default: ""
  bacio-version:
    default: ""
  bacio-cmake-args:
    default: ""
  bufr-version:
    default: ""
  bufr-cmake-args:
    default: ""
  g2-version:
    default: ""
  g2-cmake-args:
    default: ""
  g2c-version:
    default: ""
  g2c-cmake-args:
    default: ""
  ip-version:
    default: ""
  ip-cmake-args:
    default: ""
  nemsio-version:
    default: ""
  nemsio-cmake-args:
    default: ""
  sp-version:
    default: ""
  sp-cmake-args:
    default: ""
  w3emc-version:
    default: ""
  w3emc-cmake-args:
    default: ""
  repo-cache:
    description: 'Cache built packages through "actions/cache"'
    default: true
  key-prefix:
    description: "String to prepend to cache keys (for, e.g., compiler tracking)"
    default: ""
  key-suffix:
    description: "String to append to cache key (for, e.g., dependency tracking)"
    default: ""

runs:
  using: "composite"

  steps:

    - name: "Cache install dir"
      uses: actions/cache@v4
      id: deps-cache
      if: ${{ inputs.repo-cache == 'true' }}
      with:
        key: ${{ inputs.key-prefix }}-dependencies-${{ inputs.key-suffix }}
        path: nceplibs

    - name: "Build 'jasper'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.jasper-version }} && ${{ steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: jasper
        package-org: jasper-software
        cmake-args: ${{ inputs.jasper-cmake-args }}
        git-ref: ${{ inputs.jasper-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.jasper-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: ${{ inputs.key-suffix }}

    - name: "Build 'bacio'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.bacio-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-bacio
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.bacio-cmake-args }}
        git-ref: ${{ inputs.bacio-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.bacio-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: ${{ inputs.key-suffix }}

    - name: "Build 'bufr'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.bufr-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-bufr
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.bufr-cmake-args }} -DTEST_FILE_DIR=/dev/null
        git-ref: ${{ inputs.bufr-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.bufr-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: ${{ inputs.key-suffix }}

    - name: "Build 'w3emc'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.w3emc-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-w3emc
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.w3emc-cmake-args }} -DCMAKE_PREFIX_PATH="${{ github.workspace }}/nceplibs"
        git-ref: ${{ inputs.w3emc-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.w3emc-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: -bacio-${{ inputs.bacio-version }}-${{ inputs.bacio-cmake-args }}${{ inputs.key-suffix }}

    - name: "Build 'sp'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.sp-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-sp
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.sp-cmake-args }}
        git-ref: ${{ inputs.sp-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.sp-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: ${{ inputs.key-suffix }}

    - name: "Build 'ip'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.ip-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-ip
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.ip-cmake-args }} -DCMAKE_PREFIX_PATH="${{ github.workspace }}/nceplibs"
        git-ref: ${{ inputs.ip-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.ip-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: ${{ inputs.key-suffix }}

    - name: "Build 'g2c'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.g2c-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-g2c
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.g2c-cmake-args }} -DCMAKE_PREFIX_PATH"=${{ github.workspace }}/nceplibs"
        git-ref: ${{ inputs.g2c-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.g2c-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: -jasper-${{ inputs.jasper-version }}-${{ inputs.jasper-cmake-args }}${{ inputs.key-suffix }}

    - name: "Build 'g2'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.g2-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-g2
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.g2-cmake-args }} -DCMAKE_PREFIX_PATH="${{ github.workspace }}/nceplibs"
        git-ref: ${{ inputs.g2-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.g2-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: -bacio-${{ inputs.bacio-version }}-${{ inputs.bacio-cmake-args }}-w3emc-${{ inputs.w3emc-version }}-${{ inputs.w3emc-cmake-args }}-jasper-${{ inputs.jasper-version }}-${{ inputs.jasper-cmake-args }}${{ inputs.key-suffix }}

    - name: "Build 'nemsio'"
      uses: NOAA-EMC/ci-build-cmake-code@oneinstalldir
      if: ${{ inputs.nemsio-version && steps.deps-cache.outputs.cache-hit != 'true' }}
      with:
        package-name: NCEPLIBS-nemsio
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.nemsio-cmake-args }} -DCMAKE_PREFIX_PATH="${{ github.workspace }}/nceplibs"
        git-ref: ${{ inputs.nemsio-version }}
        repo-cache: false # ${{ inputs.repo-cache && inputs.nemsio-version != 'develop' }}
        key-prefix: ${{ inputs.key-prefix }}
        key-suffix: -bacio-${{ inputs.bacio-version }}-${{ inputs.bacio-cmake-args }}-w3emc-${{ inputs.w3emc-version }}-${{ inputs.w3emc-cmake-args }}${{ inputs.key-suffix }}
